/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import controller.Laberinto;
import javax.swing.JOptionPane;
import views.Tablas.Tablaslaberinto;

/**
 *
 * @author Usuario
 */
public class VistaLaberinto extends javax.swing.JDialog {

    private Tablaslaberinto mt = new Tablaslaberinto();
    private Laberinto l = new Laberinto();
    
    /**
     * Creates new form Laberinto
     */
    private VistaLaberinto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        CargarTabla();
        
       
    }
    
    
    private void crearLaberinto() {
        if (SpinnerDimension.getValue().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Faltan Datos");
        } else {
            int dimension = Integer.parseInt(SpinnerDimension.getValue().toString());
            int porcen = Integer.parseInt(SpinnerParede.getValue().toString());
            if (!(dimension < 10 || dimension > 100)) {
                actualizarTabla(dimension, porcen);
            } else {
                JOptionPane.showMessageDialog(null, "Solo se permiten dimensiones desde 10 hasta 100 ");
            }

        }
    }
    
    private void porcentaje(){
        if (SpinnerDimension.getValue().toString().isEmpty() || SpinnerParede.getValue().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Faltan Datos para generar por porcentaje");
        } else {
            int dimension = Integer.parseInt(SpinnerDimension.getValue().toString());
            int porcen = Integer.parseInt(SpinnerParede.getValue().toString());
            if (porcen >= 40 && porcen <= 60) {
                actualizarTabla(dimension, porcen);
            } else {
                JOptionPane.showMessageDialog(null, "Solo se permite un porcentaje del 40% al 60%");
            }

        }
    }
    
    private void actualizarTabla(int dimension, int porcentaje) {
    String[][] nuevaMatriz = l.generarLaberinto(dimension, porcentaje);
    l.verificarPorcentaje(nuevaMatriz, porcentaje);
    Tablaslaberinto nuevoModelo = new Tablaslaberinto(); 
    nuevoModelo.setLaberinto(nuevaMatriz);
    jTablelabrinto.setModel(nuevoModelo);
    jTablelabrinto.updateUI();
}


    public void CargarTabla() {
        SpinnerDimension.setValue(10);
        SpinnerParede.setValue(50);
        int dimension = Integer.parseInt(SpinnerDimension.getValue().toString());
        int porcen = Integer.parseInt(SpinnerParede.getValue().toString());
        mt.setLaberinto(l.generarLaberinto(dimension,porcen));
        jTablelabrinto.setModel(mt);
        jTablelabrinto.updateUI();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablelabrinto = new javax.swing.JTable();
        jButtoncrear = new javax.swing.JButton();
        BtnPorcentaje = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SpinnerDimension = new javax.swing.JSpinner();
        SpinnerParede = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jTablelabrinto.setBackground(new java.awt.Color(255, 255, 255));
        jTablelabrinto.setForeground(new java.awt.Color(0, 0, 0));
        jTablelabrinto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablelabrinto.setAlignmentX(5.0F);
        jTablelabrinto.setCellSelectionEnabled(true);
        jTablelabrinto.setGridColor(new java.awt.Color(255, 255, 255));
        jTablelabrinto.setRequestFocusEnabled(false);
        jTablelabrinto.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTablelabrinto.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTablelabrinto.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTablelabrinto.setShowGrid(false);
        jTablelabrinto.setSurrendersFocusOnKeystroke(true);
        jTablelabrinto.getTableHeader().setResizingAllowed(false);
        jTablelabrinto.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTablelabrinto);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(130, 150, 520, 400);

        jButtoncrear.setText("Generar");
        jButtoncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncrearActionPerformed(evt);
            }
        });
        jPanel2.add(jButtoncrear);
        jButtoncrear.setBounds(540, 60, 90, 23);

        BtnPorcentaje.setText("Cambiar porcentaje de paredes");
        BtnPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPorcentajeActionPerformed(evt);
            }
        });
        jPanel2.add(BtnPorcentaje);
        BtnPorcentaje.setBounds(460, 110, 230, 23);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Laberinto");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(50, 10, 200, 40);

        jLabel2.setText("Dimension:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(80, 60, 80, 16);

        jLabel3.setText("Porcentaje de paredes:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(80, 110, 150, 16);
        jPanel2.add(SpinnerDimension);
        SpinnerDimension.setBounds(220, 60, 64, 22);
        jPanel2.add(SpinnerParede);
        SpinnerParede.setBounds(220, 110, 64, 22);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(6, 0, 790, 562);

        setSize(new java.awt.Dimension(814, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtoncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncrearActionPerformed
        crearLaberinto();        // TODO add your handling code here:

    }//GEN-LAST:event_jButtoncrearActionPerformed

    private void BtnPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPorcentajeActionPerformed
    porcentaje();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPorcentajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaLaberinto dialog = new VistaLaberinto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPorcentaje;
    private javax.swing.JSpinner SpinnerDimension;
    private javax.swing.JSpinner SpinnerParede;
    private javax.swing.JButton jButtoncrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablelabrinto;
    // End of variables declaration//GEN-END:variables
}
