
package views;

import controllers.CasasController;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tablas.ModeloTablaCasas;
import tablas.ModeloTablaHomonimas;

/**
 *
 * @author Usuario
 */
public class VistaCasas extends javax.swing.JDialog {
    private ModeloTablaCasas mt = new ModeloTablaCasas();
    private ModeloTablaHomonimas mth = new ModeloTablaHomonimas();
    CasasController c = new CasasController();
    /**
     * Creates new form VistaCasas
     */
    public VistaCasas(java.awt.Frame parent, boolean modal) throws IOException {
        super(parent, modal);
        initComponents();
        cargarTabla();
        cargarTablaHomonimos();
    }
    
    private void guardar() throws IOException{
        if(txtCasa.getText().isEmpty() || txtAncho.getText().isEmpty() || txtLargo.getText().isEmpty() || txtPisos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Datos no ingresados");
        }else
            c.guardarCasa(txtCasa.getText().trim(), Float.parseFloat(txtAncho.getText()), Float.parseFloat(txtLargo.getText()), Integer.parseInt(txtPisos.getText()));
        cargarTabla();
        cargarTablaHomonimos();
        limpiar();
        
    }
    
    private void limpiar(){
        txtCasa.setText("");
        txtAncho.setText("");
        txtLargo.setText("");
        txtPisos.setText("");
    }
    
    public void cargarTabla() throws IOException{
        mt.setMatrizCasas(c.listarCasas());
        jTable1.setModel(mt);
        jTable1.updateUI();
    }
    
    public void cargarTablaHomonimos() throws IOException{
        mth.setDatos(c.obtenerCasasHomonimasParaTabla());
        jTable2.setModel(mth);
        jTable2.updateUI();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCasa = new javax.swing.JTextField();
        txtAncho = new javax.swing.JTextField();
        txtLargo = new javax.swing.JTextField();
        txtPisos = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Casas");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel1.setText("VERIFICACIÓN DE CASAS HOMONIMAS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 20, 380, 32);

        jLabel2.setText("Casa");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 70, 60, 16);

        jLabel3.setText("Ancho");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 110, 60, 16);

        jLabel4.setText("Largo");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(310, 70, 80, 16);

        jLabel5.setText("Nro de Pisos");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(310, 110, 110, 16);

        txtCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCasaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCasa);
        txtCasa.setBounds(140, 70, 71, 22);
        jPanel1.add(txtAncho);
        txtAncho.setBounds(140, 110, 70, 22);

        txtLargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLargoActionPerformed(evt);
            }
        });
        jPanel1.add(txtLargo);
        txtLargo.setBounds(480, 70, 70, 22);
        jPanel1.add(txtPisos);
        txtPisos.setBounds(480, 110, 70, 22);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar);
        btnGuardar.setBounds(580, 90, 72, 23);

        jLabel6.setText("Casas Homonimas");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 150, 120, 16);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 180, 570, 150);

        jLabel7.setText("Detalles de Casas Homonimas:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 350, 180, 16);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(70, 380, 570, 140);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 680, 580);

        setSize(new java.awt.Dimension(698, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCasaActionPerformed
        
    }//GEN-LAST:event_txtCasaActionPerformed

    private void txtLargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLargoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            guardar();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "no puedes guardar");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCasas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCasas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCasas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCasas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaCasas dialog = null;
                try {
                    dialog = new VistaCasas(new javax.swing.JFrame(), true);
                } catch (IOException ex) {
                    Logger.getLogger(VistaCasas.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtAncho;
    private javax.swing.JTextField txtCasa;
    private javax.swing.JTextField txtLargo;
    private javax.swing.JTextField txtPisos;
    // End of variables declaration//GEN-END:variables
}
