/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import controller.Laberinto;
import javax.swing.JOptionPane;
import views.Tablas.Tablaslaberinto;




/**
 *
 * @author Usuario
 */
public class VistaLaberinto extends javax.swing.JDialog {
   
    private Tablaslaberinto mt = new Tablaslaberinto();
    private Laberinto l = new Laberinto();
    

    /**
     * Creates new form Laberinto
     */
    private  VistaLaberinto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        CargarTabla();
    }
    
    private void crearLaberinto(){
        if(txtDimension.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "rogel es gay");
        } else{
            mt.setLaberinto(l.generarLaberinto(Integer.parseInt(txtDimension.getText())));
            jTablelabrinto.setModel(mt);
            jTablelabrinto.updateUI();
        }
    }
    
    public void CargarTabla(){ 
        txtDimension.setText("5");
        mt.setLaberinto(l.generarLaberinto(Integer.parseInt(txtDimension.getText())));
        jTablelabrinto.setModel(mt);
        jTablelabrinto.updateUI();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablelabrinto = new javax.swing.JTable();
        jButtoncrear = new javax.swing.JButton();
        jButtonreiniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDimension = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jTablelabrinto.setBackground(new java.awt.Color(255, 255, 255));
        jTablelabrinto.setForeground(new java.awt.Color(0, 0, 0));
        jTablelabrinto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablelabrinto.setGridColor(new java.awt.Color(255, 255, 255));
        jTablelabrinto.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTablelabrinto.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTablelabrinto.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTablelabrinto.setSurrendersFocusOnKeystroke(true);
        jTablelabrinto.getTableHeader().setResizingAllowed(false);
        jTablelabrinto.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTablelabrinto);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(140, 180, 530, 340);

        jButtoncrear.setText("CREAR");
        jButtoncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncrearActionPerformed(evt);
            }
        });
        jPanel2.add(jButtoncrear);
        jButtoncrear.setBounds(640, 100, 72, 23);

        jButtonreiniciar.setText("REINICIAR");
        jButtonreiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonreiniciarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonreiniciar);
        jButtonreiniciar.setBounds(640, 40, 84, 23);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Laberinto");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(50, 10, 200, 40);

        jLabel2.setText("Dimension:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(80, 60, 80, 16);

        jLabel3.setText("Porcentaje de paredes:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(80, 110, 150, 16);

        txtDimension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDimensionActionPerformed(evt);
            }
        });
        jPanel2.add(txtDimension);
        txtDimension.setBounds(210, 60, 71, 22);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(6, 0, 790, 562);

        setSize(new java.awt.Dimension(814, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtoncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncrearActionPerformed
    crearLaberinto();        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtoncrearActionPerformed

    private void jButtonreiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonreiniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonreiniciarActionPerformed

    private void txtDimensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDimensionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDimensionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaLaberinto dialog = new VistaLaberinto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoncrear;
    private javax.swing.JButton jButtonreiniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablelabrinto;
    private javax.swing.JTextField txtDimension;
    // End of variables declaration//GEN-END:variables
}
